### ISSUE TITLE
.site-header

### ISSUE THREAD

**Issue by brody182** [mattbanks/Genesis-Starter-Child-Theme#15]
why am i seeing this in the header?

.site-header {
    background: url("http://localhost/desertcove-new/wp-content/themes/desertcove/images/header.png") no-repeat scroll 0% 0% transparent !important; }

how do i get rid of it?

**Comment by mattbanks** [comment]
That has to do with Genesis using a header image instead of text, not something with the base child theme. You could turn off the `genesis-custom-header` support in [functions.php#L114-L117](https://github.com/mattbanks/Genesis-Starter-Child-Theme/blob/master/functions.php#L114-L117) if you wanted to totally disable that functionality.

**Comment by brody182** [comment]
that setting was carried over from another theme.. If i switch to genesis it doesn't show, only when i switch to child theme
